apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: awala-endpoint
requires:
  - path: skaffold-deps.yml
build:
  artifacts:
    - image: dev.local/awala-endpoint
  local:
    push: false
manifests:
  rawYaml:
    - k8s/*.yml
deploy:
  kubectl: {}
  statusCheck: true
  statusCheckDeadlineSeconds: 240
  tolerateFailuresUntilDeadline: true
