apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: awala-endpoint
build:
  artifacts:
    - image: dev.local/awala-endpoint
  local:
    push: false
manifests:
  rawYaml:
    - k8s/*.yml
deploy:
  statusCheckDeadlineSeconds: 180
  tolerateFailuresUntilDeadline: true
  kubectl: {}
