apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mock-gateway
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: gateway
          image: mockserver/mockserver:5.15.0
          env:
            - name: MOCKSERVER_SERVER_PORT
              value: "8080"
          livenessProbe:
            httpGet:
              path: /mockserver/status
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 3
