apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mock-app
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
      labels:
        app.kubernetes.io/name: awala-endpoint
    spec:
      containers:
        - name: app
          image: mockserver/mockserver:5.15.0
          env:
            - name: MOCKSERVER_SERVER_PORT
              value: "8080"
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: mock-app-trigger
spec:
  broker: awala-endpoint-broker
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: mock-app
