apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: awala-endpoint-pohttp-server
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: server
          image: dev.local/awala-endpoint
          args: [pohttp-server]
          env:
            - name: MONGODB_USER
              valueFrom:
                configMapKeyRef:
                  name: credentials
                  key: mongodb_username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: mongodb_password

            - name: KS_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: vault_token

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: mock-aws-kms
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: aws_kms_secret_access_key
            - name: AWS_KMS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: mock-aws-kms
                  key: endpoint
          envFrom:
            - configMapRef:
                name: pohttp
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 5
            failureThreshold: 2
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 5
            failureThreshold: 2
            timeoutSeconds: 3
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: awala-endpoint-sink-binding
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: awala-endpoint-pohttp-server
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: awala-endpoint-broker
