apiVersion: v1
kind: ConfigMap
metadata:
  name: pohttp
data:
  ENDPOINT_VERSION: "1.0.0dev1"

  INTERNET_ADDRESS: example.com

  MONGODB_URI: mongodb://mongodb.default
  MONGODB_DB: endpoint

  ACTIVE_ID_KEY_REF: arn:aws:kms:eu-west-2:111122223333:key/800d5768-3fd7-4edd-a4b8-4c81c3e4c147
  ACTIVE_ID_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhdIVqKxn+Fce40n08bsZdZXDKtp7IoFwyFmuJ3CM3BoXgkaR1o9cIqC84NSed8S0nG9+rRWy2/iQl/c3qaPLQUxxy4eFMJsztbwyTa+vA+PwRYfhfPxsveXWckir2k2p/ePjsiRw2Cawsrx93wHYIoY0w5Iaa0lQkjx0w7lrIRn9Uavh0xO2OQy/B6EQNrzIF763P+A7hX3abnIBsvvColTpLRFbYd9UBclfl1FYukjoVd9ybm5+CqrtZkThrMaKMUz/9ynEV1Rfw+s+8NhhwxXOqFW2cLkyPVaH2pjfEfVUuvr/ViqNPz0eUB96jv9pCtgJHkWbwDQr4N2s6VEY6QIDAQAB

  # Mock AWS KMS (used by WebCrypto KMS)
  KMS_ADAPTER: AWS
  AWS_KMS_REGION: eu-west-2

  PRIVATE_KEY_STORE_ADAPTER: "1"
  KS_VAULT_URL: http://vault.default
  KS_VAULT_KV_PREFIX: endpoint-keys
