apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: awala-endpoint-pohttp-client
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: queue
          image: dev.local/awala-endpoint
          args: [queue]
          readinessProbe:
            httpGet:
              path: /
            initialDelaySeconds: 1
          env:
            - name: ENDPOINT_VERSION
              value: "1.0.0dev1"
            - name: MONGODB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: credentials
                  key: mongodb_username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: mongodb_password
            - name: MONGODB_URI
              value: mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@mongodb

            # Mock AWS KMS (used by WebCrypto KMS)
            - name: KMS_ADAPTER
              value: AWS
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: mock-aws-kms
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: aws_kms_secret_access_key
            - name: AWS_KMS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: mock-aws-kms
                  key: endpoint
            - name: AWS_KMS_REGION
              value: eu-west-2
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: awala-endpoint-pohttp-client-sink-binding
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: awala-endpoint-pohttp-client
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: awala-endpoint-broker
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: awala-endpoint-pohttp-client-trigger
spec:
  broker: awala-endpoint-broker
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: awala-endpoint-pohttp-client
