apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: awala-endpoint-pohttp-server
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
      labels:
        app.kubernetes.io/name: awala-endpoint
    spec:
      containers:
        - name: server
          image: dev.local/awala-endpoint
          args: [server]
          readinessProbe:
            httpGet:
              path: /
            initialDelaySeconds: 1
          env:
            - name: ENDPOINT_VERSION
              value: "1.0.0dev1"

            - name: MONGODB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: credentials
                  key: mongodb_username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: mongodb_password
            - name: MONGODB_URI
              value: mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@mongodb.default
            - name: INTERNET_ADDRESS
              value: "example.com"
            - name: ACTIVE_ID_KEY_REF
              value: "arn:aws:kms:eu-west-2:111122223333:key/800d5768-3fd7-4edd-a4b8-4c81c3e4c147"
            - name: KMS_ADAPTER
              value: "AWS"
            - name: PRIVATE_KEY_STORE_ADAPTER
              value: "1"
            - name: KS_VAULT_URL
              value: "example.com"
            - name: KS_VAULT_TOKEN
              value: "b64enc"
            - name: KS_VAULT_KV_PREFIX
              value: "prefix"

            # Mock AWS KMS (used by WebCrypto KMS)
            - name: KMS_ADAPTER
              value: AWS
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: mock-aws-kms
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: aws_kms_secret_access_key
            - name: AWS_KMS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: mock-aws-kms
                  key: endpoint
            - name: AWS_KMS_REGION
              value: eu-west-2
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: awala-endpoint-sink-binding
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: awala-endpoint
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: awala-endpoint-broker
