apiVersion: batch/v1
kind: Job
metadata:
  name: vault-config
spec:
  ttlSecondsAfterFinished: 180
  template:
    metadata:
      name: "vault-config"
    spec:
      restartPolicy: OnFailure

      initContainers:
        - name: startup-delay
          image: busybox
          command: ["sleep", "5s"]

      containers:
        - name: vault-config
          image: vault:1.13.2
          imagePullPolicy: IfNotPresent
          command:
            - vault
            - secrets
            - enable
            - "-path=endpoint-keys"
            - kv-v2
          env:
            - name: VAULT_ADDR
              value: "http://vault.default"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: vault_token
