apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vault
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: vault
          image: vault:1.13.2
          imagePullPolicy: IfNotPresent
          command:
            - vault
            - server
            - "-dev"
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: vault_token
            - name: VAULT_DEV_LISTEN_ADDRESS
              value: "0.0.0.0:8080"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: vault-config
spec:
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      name: "vault-config"
      labels:
        app.kubernetes.io/name: awala-endpoint
    spec:
      restartPolicy: OnFailure

      initContainers:
        - name: startup-delay
          image: busybox
          command: ["sleep", "30s"]

      containers:
        - name: vault-config
          image: vault:1.13.2
          imagePullPolicy: IfNotPresent
          command:
            - vault
            - secrets
            - enable
            - "-path=endpoint-keys"
            - kv-v2
          env:
            - name: VAULT_ADDR
              value: "http://vault.default"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: vault_token
