apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vault
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
      labels:
        app.kubernetes.io/name: awala-endpoint
    spec:
      containers:
        - name: vault
          image: vault:1.13.2
          imagePullPolicy: IfNotPresent
          command:
            - vault
            - server
            - "-dev"
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: vault_token
            - name: VAULT_DEV_LISTEN_ADDRESS
              value: "0.0.0.0:8080"
