title: Awala Internet Endpoint

markdown: kramdown

baseurl: /awala-endpoint-internet
destination: ../build/docs
remote_theme: pmarsceill/just-the-docs@v0.2.7-r

footer_content: "Copyright &copy; 2023 by Relaycorp, Inc."

color_scheme: dark

search_enabled: false

aux_links:
  "GitHub project":
    - "https://github.com/relaycorp/awala-endpoint-internet"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
